name: Submodule Updates

on:
  schedule:
    - cron: '0 0 * * 3,0'
  workflow_dispatch:

jobs:
  build:
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ProbeZS Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAGE_TOKEN }}
          fetch-depth: 0
      - name: Update Submodules
        run: git submodule update --remote
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: Update Submodules
